// const dateformat = require('dateformat');
let CSV2JSONConverter = require('./classes/converter.js');
let jsonHelper = require('./classes/jsonHelper.js');
let Merge = require('./classes/merger.js');

//Merge exectemp and Autogenerated files
// let m = new Merge();
// m.mergeCsv("./data/csv/autogen/diagnostic_doc.csv", "./data/csv/exectemp/diagnostic_doc.csv").then( data =>{
//   // console.log(data);
//   m.writeCsvData(data, "./data/csv/merged/diagnostic_doc.csv");
// });

//CSV2JSON
let c = new CSV2JSONConverter("./data/csv/merged/", "./data/json/");
c.convertAll().then(data=>{
  console.log(data);
});

// console.log("Joy, Joel[Enter] Radhakrishnan, Anju[Enter] D'souza, Warren Tristen[Enter] Paul, Jonathan[Enter]".replace(/\[Enter\]/g,"\n"));
// //JSON inserter
// let dt = new Date();
// let jh = new jsonHelper();
// let jsonObj = require('./data/json/test.json');
// let outdata = jh.updateValue(jsonObj,"COLUMNS", dateformat(dt, 'mmm dd, yyyy hh:MM').toString().toUpperCase(),"[A-Z][A-Z][A-Z] [0-9][0-9], [0-9][0-9][0-9][0-9] [0-9][0-9]:[0-9][0-9]");
// c.writeJSON(outdata, './data/json/testnew.json');

// console.log(dateformat(dt, 'dddd, mmmm dS, yyyy, h:MM:ss TT'));
// console.log(dateformat(dt, 'mmm dd, yyyy hh:MM').toString().toUpperCase());
