let Merge = require('./classes/merger.js');

//Merge exectemp and Autogenerated files
let m = new Merge();
m.mergeCsv("./data/csv/autogen/reminders.csv", "./data/csv/exectemp/reminders.csv").then( data =>{
  // console.log(data);
  m.writeCsvData(data, "./data/csv/merged/rem.csv");
});
